### ISSUE TITLE
Weird empty space below `.versionDisplay` in the page action popup

### ISSUE THREAD

**Issue by Jee-Hex** [kkapsner/CanvasBlocker#753]
## Description

There is this weird empty space below `.versionDisplay` in the page action popup (when compared to the browser action) that goes away when I added `display:none;` to `.versionDisplay`. 

## Expected Behaviour

Similar amount of empty space below `.versionDisplay` in both the browser action and page action popup.

## Current Behaviour

So much more empty space below `.versionDisplay` in the page action popup than in the browser action popup.

## Possible Solution

Disabling `padding-bottom: 1.5em;` in [`pageAction.css:5`](https://github.com/kkapsner/CanvasBlocker/blob/61132e010587bd9e1d5d50a61b9f2a43c94f736b/pageAction/pageAction.css#L8) and then flipping the `display:none;` added to `.versionDisplay` on and off seem to work relatively well in getting rid of that empty space. Adding 

```css
@-moz-document url("moz-extension://[canvasblocker-webext-uuid]/pageAction/pageAction.html") {
	body {
		padding-bottom: 2px !important;
	}
}
```

to `userContent.css` also worked for me.

## Context

Feel free to close as INVALID/WONTFIX if this was intentional.

## Your Environment

* CanvasBlocker Version used: 1.10.1/1.11
* Firefox version incl. 32- or 64-bit: 128.9.0esr
* Operating System and version (desktop or mobile): Desktop
